name: Hello World

env:
  GLOBAL_VAR: "workflow-level"
  USERNAME: "orko"

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Name to greet"
        required: false
        default: "World"
  push:
    branches:
      - main

jobs:


  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Show env variables
        run: echo "The global variable is ${{env.GLOBAL_VAR}} and the username is ${{env.USERNAME}}"

      - name: Run a simple script
        run: echo The username is ${{inputs.username}}

  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display file in the Repository
        run: ls -la
      - name: Show current DIR
        run: pwd

  