name: Concerrency and if else Example

on:
  push:
    branches:
      - main
      - feature/*

concurrency:
  group: my-concurrency-group
  cancel-in-progress: true

jobs:
  if-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message if branch is main
        if: github.ref == 'refs/heads/main'
        run: echo "This is the main branch."

      - name: Print output
        run: |
          cat output.txt || echo "No output file found."

  test-file-sharing:
    runs-on: ubuntu-latest

    steps:
      - name: Print output
        run: |
          cat output.txt || echo "No output file found."
